# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20170306_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(default='/dev_static/default_img/default_user.png', upload_to=utils.get_file_path),
        ),
    ]
