# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20170306_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(default='/user/default_user.png', upload_to=utils.get_file_path),
        ),
    ]
