# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20170306_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='C:\\Users\\micha\\Desktop\\academie_diplom\\worst_buy\\staticfiles\\default_img\\default_user.png', upload_to=utils.get_file_path),
        ),
    ]
