# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20170326_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True, validators=[products.models.validate_rating]),
        ),
    ]
