# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 11:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0014_auto_20170326_1445'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set([('commenter', 'product')]),
        ),
    ]
