# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_auto_20170326_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='edit_amount',
            field=models.IntegerField(default=0),
        ),
    ]
