# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-27 13:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_auto_20170327_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='items',
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='counter',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_in_cart', to='products.Product'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='prod_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
