# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-04 17:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0019_auto_20170504_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commenter',
            new_name='author',
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together=set([('author', 'product')]),
        ),
    ]
