# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-14 16:23
from __future__ import unicode_literals

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_auto_20170504_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.FileField(default='../static/default_img/default_prod.jpg', upload_to=utils.get_file_path),
        ),
    ]
