# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 09:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0021_auto_20170514_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryOfPurchases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_in_history', to='products.ShoppingCart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_username', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
