# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_historyofpurchases'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historyofpurchases',
            name='cart',
        ),
        migrations.AddField(
            model_name='historyofpurchases',
            name='cart',
            field=models.ManyToManyField(related_name='cart_in_history', to='products.ShoppingCart'),
        ),
    ]
