# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20170522_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historyofpurchases',
            name='cart',
        ),
        migrations.AddField(
            model_name='historyofpurchases',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to=utils.get_file_path),
        ),
    ]
