# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-22 09:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20170522_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historyofpurchases',
            name='pdf_file',
        ),
        migrations.AddField(
            model_name='historyofpurchases',
            name='history',
            field=models.TextField(blank=True, null=True),
        ),
    ]
